import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

// Load Simplon Norm locally
const simplonNorm = localFont({
  src: '../../fonts/simplon-norm.woff2',
  variable: '--font-simplon',
  display: 'swap',
});

// Load Adobe Caslon Pro locally
const adobeCaslon = localFont({
  src: '../../fonts/adobe-caslon-pro.woff2',
  variable: '--font-caslon',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${simplonNorm.variable} ${adobeCaslon.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
